_target_: megascale

batch_size: 4
num_workers: 16
pin_memory: True

alphabet:
  name: esm
  featurizer: megascale
  featurizer_cfg:
    single_mut: false
    mut_seq: false
    saprot_lmdb_path: processed_data/saprot_lmdb/wt_mlm_db/
